#!/usr/bin/env python

import sys

import roslib
pkg = 'hrpsys_gazebo_atlas'
plugin='atlas_hrpsys_dashboard.AtlasHrpsysDashboard'


import imp
try:
    imp.find_module(pkg)
except:
    roslib.load_manifest(pkg)

from rqt_gui.main import Main

import hrpsys_gazebo_atlas
import hrpsys_gazebo_atlas.atlas_hrpsys_dashboard

main = Main()
sys.exit(main.main(sys.argv, standalone=(pkg+'.'+plugin)))
