hrpsys_gazebo_configuration:
  publish_joint_state:
    topic: /joint_states
    step: 25
## velocity feedback for joint control, use parameter gains/joint_name/p_v
#  use_velocity_feedback: true
## synchronized hrpsys and gazebo
# use_synchronized_command: false
# name of robot (using for namespace)
  robotname: HRP3HAND_L
# joint_id (order) conversion from gazebo to hrpsys, joint_id_list[gazebo_id] := hrpsys_id
  joint_id_list: [0, 1, 2, 3, 4, 5]
# joints list used in gazebo, sizeof(joint_id_list) == sizeof(joints)
  joints:
    - L_THUMBCM_Y
    - L_THUMBCM_P
    - L_INDEXMP_R
    - L_INDEXMP_P
    - L_INDEXPIP_R
    - L_MIDDLEPIP_R
## jointid:
  gains:
    L_INDEXMP_R:   {p: 10.0, d:   0.01, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    L_INDEXMP_P:   {p: 10.0, d:   0.01, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    L_INDEXPIP_R:  {p: 10.0, d:   0.01, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    L_MIDDLEPIP_R: {p: 10.0, d:   0.01, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    L_THUMBCM_Y:   {p: 10.0, d:   0.01, i: 0.0, i_clamp: 0.0, p_v: 10.0}
    L_THUMBCM_P:   {p: 10.0, d:   0.01, i: 0.0, i_clamp: 0.0, p_v: 10.0}
